apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: covid-vaccine-notification
  name: covid-vaccine-notification
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-vaccine-notification
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: covid-vaccine-notification
    spec:
      containers:
        - image:
          imagePullPolicy: IfNotPresent
          name: covid-vaccine-notification