apiVersion: v1
kind: Service
metadata:
  name: covid-service
spec:
  selector:
    app: covid-vaccine-notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer